main: me.rey.clans.Main
name: Clans
version: 1.0.0
author: rey
depend: [Warriors, ReinforcedCore, Parser]
commands:
    focus:
    c:
        aliases: [clan, clans, faction, factions]
    ac:
        aliases: [allychat]
    cc:
        aliases: [clanchat]